const SPINE_LENGTH = 34;
const HEAD_DIAMETER = 18;

const CHEST_LENGTH = (SPINE_LENGTH / 2) + 2;
const HAND_LENGTH = 12
const LEG_LENGTH = 14;

const MOVEMENT_SUM = 3;

const LEFT_ARROW_KEY_CODE = 37;
const RIGHT_ARROW_KEY_CODE = 39;

export {SPINE_LENGTH, HEAD_DIAMETER, CHEST_LENGTH, HAND_LENGTH, LEG_LENGTH, MOVEMENT_SUM, LEFT_ARROW_KEY_CODE, RIGHT_ARROW_KEY_CODE};
